[Info]
ID=Clean-up Windows
Ver=1.0
Desc=This script will download an improved version of Microsoft cleanmgr.exe, called Cleanmgr+ (also from Mirinsoft).\n\nThe tool can perform a search on the hard disk for files that can be deleted from your computer without affecting its functionality or your personal files.
Dev=Mirinsoft
DevURL=https://www.mirinsoft.com
WinVer=Compatible with Windows 10
Evaluation=Recommended
EvaluationColor=009e5e

[Scripts]
File1=GetFile,http://www.imirin.com/files/16/Cleanmgr/1/Cleanmgr.zip


