[Info]
ID=Disable Sync
Ver=1.0
Desc=It doesn't really affect you if you're not using a Microsoft Account, but this script will at least disable the Sync settings from the Settings app.
Dev=Federico Dossena
DevURL=https://github.com/adolfintel/Windows10-Privacy
WinVer=Compatible with Windows 10
Evaluation=Recommended
EvaluationColor=009e5e

[Scripts]
Task1=DetectRegValue,reg query "HKLM\Software\Policies\Microsoft\Windows\SettingSync" /v DisableSettingSync,STDOUT
Task2=DetectRegValue,reg query "HKLM\Software\Policies\Microsoft\Windows\SettingSync" /v DisableSettingSyncUserOverride,STDOUT
File1=Exec,reg add "HKLM\Software\Policies\Microsoft\Windows\SettingSync" /v DisableSettingSync /t REG_DWORD /d 2 /f,STDOUT
File2=Exec,reg add "HKLM\Software\Policies\Microsoft\Windows\SettingSync" /v DisableSettingSyncUserOverride /t REG_DWORD /d 1 /f,STDOUT













