[Info]
ID=Download install_wim_tweak.exe
Ver=1.0
Desc=This script will download "install_wim_tweak.exe" which can uninstall pre-installed apps and remove Windows components with a single command. You can also use the built-in scripts in Debotnet for removing the default UWP apps. Of course, not everything can be uninstalled in this manner. For the more difficult apps, use the install_wim_tweak.exe utility.\n\nYou may not want to do any of this in post setup; perhaps you want to make changes directly to the install.wim. These direct Image modfication can be done with install_wim_tweak.exe\n\nThe file is hosted on @Deskmodder.de (https://www.deskmodder.de/blog/2018/06/24/install_wim_tweak-apps-und-systemfunktionen-auch-nach-der-installation-entfernen-windows-10)
Dev=Wnuowski, updated by Win Toolkit Programmer
DevURL=https://msfn.org/board/topic/152688-win6x_registry_tweak/
WinVer=Compatible with Windows 10
Evaluation=Limited
EvaluationColor=ffd45e

[Scripts]
File1=GetFile,https://www.deskmodder.de/blog/wp-content/uploads/2018/06/install-wim-tweak.zip




