[Info]
ID=Download Windows updates
Ver=1.0
Desc=Once you get to the desktop, go to Settings > Updates and security, and let it download all the updates.\nReboot and repeat until no more updates are available.\n\nThis is important because Windows Update may interfere with our activities.\n\nRun this script to open the Windows update.
Dev=Mirinsoft
DevURL=https://www.mirinsoft.com
WinVer=Compatible with Windows 10
Evaluation=Recommended
EvaluationColor=009e5e

[Scripts]
File1=Start,ms-settings:windowsupdate-action
















