[Info]
ID=Open Privacy settings
Ver=1.0
Desc=At the end of Windows 10 setup process, create a local account, don't use Cortana and turn off everything in the privacy settings.\n\nIf you already installed Windows with the default settings, go to Start > Settings > Privacy to turn them off. You should also go to Account and disconnect your Microsoft account because this guide will prevent it from working properly.\n\nThis Script will ONLY open Windows 10 privacy settings.
Dev=Mirinsoft
DevURL=https://www.mirinsoft.com
WinVer=Compatible with Windows 10
Evaluation=Recommended
EvaluationColor=009e5e

[Scripts]
File1=Start,ms-settings:privacy-general









