[Info]
ID=Remove Microsoft Store
Ver=1.0
Desc=If you no longer want or use an app, then you could uninstall the app to remove it and free up space on the drive.\n\nThis script will remove the app Microsoft Store from current account only.
Dev=Mirinsoft
DevURL=https://www.mirinsoft.com
WinVer=Compatible with Windows 10
Warning=NOT RECOMMENDED!
Evaluation=Not Recommended
EvaluationColor=c14566

[Scripts]
File1=Exec,powershell -command "Get-AppxPackage *Microsoft.WindowsStore* | Remove-AppxPackage",SHOWCLI














