[Info]
ID=Removing Telemetry
Ver=1.0
Desc=This script will remove telemetry and other unnecessary services.
Dev=Federico Dossena
DevURL=https://github.com/adolfintel/Windows10-Privacy
WinVer=Compatible with Windows 10

[Scripts]
File1=Exec,sc delete DiagTrack,STDOUT
File2=Exec,sc delete dmwappushservice,STDOUT
File3=Exec,sc delete WerSvc,STDOUT
File4=Exec,sc delete OneSyncSvc,STDOUT
File5=Exec,sc delete MessagingService,STDOUT
File6=Exec,sc delete wercplsupport,STDOUT
File7=Exec,sc delete PcaSvc,STDOUT
File8=Exec,sc config wlidsvc start=demand,STDOUT
File9=Exec,sc delete wisvc,STDOUT
File10=Exec,sc delete RetailDemo,STDOUT
File11=Exec,sc delete diagsvc,STDOUT
File12=Exec,sc delete shpamsvc,STDOUT
File13=Exec,sc delete TermService,STDOUT
File14=Exec,sc delete UmRdpService,STDOUT
File15=Exec,sc delete SessionEnv,STDOUT
File16=Exec,sc delete TroubleshootingSvc,STDOUT
File17=Exec,sc delete diagnosticshub.standardcollector.service,STDOUT
File18=Exec,for /f "tokens=1" %I in ('reg query "HKLM\SYSTEM\CurrentControlSet\Services" /k /f "wscsvc" ^, find /i "wscsvc"') do (reg delete %I /f),STDOUT
File19=Exec,for /f "tokens=1" %I in ('reg query "HKLM\SYSTEM\CurrentControlSet\Services" /k /f "OneSyncSvc" ^, find /i "OneSyncSvc"') do (reg delete %I /f),STDOUT
File20=Exec,for /f "tokens=1" %I in ('reg query "HKLM\SYSTEM\CurrentControlSet\Services" /k /f "MessagingService" ^, find /i "MessagingService"') do (reg delete %I /f),STDOUT
File21=Exec,for /f "tokens=1" %I in ('reg query "HKLM\SYSTEM\CurrentControlSet\Services" /k /f "PimIndexMaintenanceSvc" ^, find /i "PimIndexMaintenanceSvc"') do (reg delete %I /f),STDOUT
File22=Exec,for /f "tokens=1" %I in ('reg query "HKLM\SYSTEM\CurrentControlSet\Services" /k /f "UserDataSvc" ^, find /i "UserDataSvc"') do (reg delete %I /f),STDOUT
File23=Exec,for /f "tokens=1" %I in ('reg query "HKLM\SYSTEM\CurrentControlSet\Services" /k /f "UnistoreSvc" ^, find /i "UnistoreSvc"') do (reg delete %I /f),STDOUT
File24=Exec,for /f "tokens=1" %I in ('reg query "HKLM\SYSTEM\CurrentControlSet\Services" /k /f "BcastDVRUserService" ^, find /i "BcastDVRUserService"') do (reg delete %I /f),STDOUT
File25=Exec,for /f "tokens=1" %I in ('reg query "HKLM\SYSTEM\CurrentControlSet\Services" /k /f "Sgrmbroker" ^, find /i "Sgrmbroker"') do (reg delete %I /f),STDOUT
File26=Exec,reg add "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Siuf\Rules" /v "NumberOfSIUFInPeriod" /t REG_DWORD /d 0 /f,STDOUT
File27=Exec,reg delete "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Siuf\Rules" /v "PeriodInNanoSeconds" /f,STDOUT
File28=Exec,reg add "HKLM\SYSTEM\ControlSet001\Control\WMI\AutoLogger\AutoLogger-Diagtrack-Listener" /v Start /t REG_DWORD /d 0 /f,STDOUT
File29=Exec,reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppCompat" /v AITEnable /t REG_DWORD /d 0 /f,STDOUT
File30=Exec,reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppCompat" /v DisableInventory /t REG_DWORD /d 1 /f,STDOUT
File31=Exec,reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppCompat" /v DisablePCA /t REG_DWORD /d 1 /f,STDOUT
File32=Exec,reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\AppCompat" /v DisableUAR /t REG_DWORD /d 1 /f,STDOUT
File33=Exec,reg add "HKLM\SOFTWARE\Policies\Microsoft\MicrosoftEdge\PhishingFilter" /v "EnabledV9" /t REG_DWORD /d 0 /f,STDOUT
File34=Exec,reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\System" /v "EnableSmartScreen" /t REG_DWORD /d 0 /f,STDOUT
File35=Exec,reg add "HKCU\Software\Microsoft\Internet Explorer\PhishingFilter" /v "EnabledV9" /t REG_DWORD /d 0 /f,STDOUT
File36=Exec,reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" /v "NoRecentDocsHistory" /t REG_DWORD /d 1 /f,STDOUT
File37=Exec,reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\CompatTelRunner.exe" /v Debugger /t REG_SZ /d "%windir%\System32\taskkill.exe" /f,STDOUT
File38=Exec,reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\DeviceCensus.exe" /v Debugger /t REG_SZ /d "%windir%\System32\taskkill.exe" /f,STDOUT








